function Categories() {
  return (
    <>
    <h1>Categories</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur officiis repellat non cum sint voluptas distinctio, provident perspiciatis excepturi, accusamus nisi sequi ipsa. Voluptatibus eum autem itaque nulla nesciunt saepe labore quam eos dolorem! Tenetur dolorum ea molestiae voluptate odio, totam, nostrum nobis inventore consequuntur non voluptatibus optio eaque quae culpa minima iusto amet minus omnis velit accusamus sit. Voluptates eum facere quisquam distinctio aut, tempora culpa nobis ducimus, nulla placeat exercitationem. Accusamus reiciendis aspernatur ducimus, tempore hic inventore nesciunt deserunt, repellat, ea ipsum consequatur eveniet suscipit expedita quis repudiandae iusto non. Reiciendis doloribus laborum quis alias asperiores optio consequatur? Qui asperiores sint illo laboriosam et eligendi amet ad odio impedit rerum. Consequatur, cumque dicta! Molestias modi laboriosam, officia itaque, dolore voluptate provident vel debitis aliquam explicabo sed voluptas! Natus velit, cupiditate non repellat temporibus tempore tempora voluptatum aperiam numquam assumenda ab? Corporis dolor nulla ea magni. Exercitationem doloribus enim doloremque odit voluptatibus quo deleniti eum quasi? Pariatur iusto voluptatem vel corporis perferendis inventore facere nesciunt sequi! Rerum provident quod asperiores blanditiis quasi repudiandae facere, sequi quam praesentium fugit laudantium maiores laborum repellendus soluta officia vitae excepturi ut. Ipsum laborum eveniet temporibus, odit dignissimos minima itaque numquam possimus inventore? Est, corrupti similique sint deserunt nihil obcaecati consectetur dolores praesentium neque quae beatae perspiciatis ullam blanditiis sapiente animi exercitationem ducimus odio laboriosam laborum cupiditate nostrum et illo quaerat hic. Similique alias at, voluptates consequuntur aliquam ab. Harum commodi quasi quos dolore quo. Repudiandae cumque, a excepturi rerum molestiae velit, eaque molestias quod nisi, fuga voluptatum animi quasi explicabo porro quis beatae saepe. Tempora assumenda enim aut numquam necessitatibus? Repellendus voluptates inventore pariatur numquam magni voluptatum iste repudiandae. Nihil repellat quas, quos facilis tenetur, aperiam cupiditate deleniti culpa soluta maiores aspernatur, nam consequatur. Voluptatibus sint quo maiores deserunt magnam! Delectus, vel magni!</p>
    </>
  )
}

export default Categories